# Generated by Django 4.1.1 on 2022-09-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Zip',
            new_name='zip',
        ),
    ]
